defaults:
  - base_model

name: 'canary-1b-v2_finetuned_spec-aug'

# Evaluation parameters
model_id: null
restore_from: 'artifact://canary-1b-v2-finetune_26722971:latest/canary-1b-v2-finetune.nemo'
nemo_model: true
language: 'da'
