defaults:
  - base_model

name: 'canary_finetune_spec-aug_speed-perturbations'

# Evaluation parameters
model_id: null
restore_from: 'artifact://canary-finetune_spec-aug_speed-perturbations_27154105:latest/canary-finetune_spec-aug_speed-perturbations.nemo'
nemo_model: true
language: 'da'
