defaults:
  - base_model

name: 'canary_finetune_spec-aug_pitch-shift'

# Evaluation parameters
model_id: null
restore_from: 'artifact://canary-finetune_spec-aug_pitch-shift_27111634:latest/canary-finetune_spec-aug_pitch-shift.nemo'
nemo_model: true
language: 'da'
