defaults:
  - base_model

name: 'canary_finetune_speed-perturbations_pitch-shift'

# Evaluation parameters
model_id: null
restore_from: 'artifact://canary-finetune_speed-perturbations_pitch-shift_27154122:latest/canary-finetune_speed-perturbations_pitch-shift.nemo'
nemo_model: true
language: 'da'
