defaults:
  - base_model

name: 'parakeet_finetune_speed-perturbations_pitch-shift'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-finetune_speed-perturbations_pitch-shift_27154178:latest/parakeet-finetune_speed-perturbations_pitch-shift.nemo'
nemo_model: true
