defaults:
  - base_model

name: 'parakeet_finetune_spec-aug_pitch-shift'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-finetune_spec-aug_pitch-shift_27111643:latest/parakeet-finetune_spec-aug_pitch-shift.nemo'
nemo_model: true