defaults:
  - base_model

name: 'parakeet_finetune_spec-aug_speed-perturbations'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-finetune_spec-aug_speed-perturbations_27154160:latest/parakeet-finetune_spec-aug_speed-perturbations.nemo'
nemo_model: true
