defaults:
  - base_model

name: 'parakeet_finetune_spec-aug'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-finetune_spec-aug_27154169:latest/parakeet-finetune_spec-aug.nemo'
nemo_model: true