defaults:
  - base_model

name: 'parakeet-tdt-0.6b-v3_finetune_spec-aug_speed-perturbations'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-tdt-0.6b-v3-finetune_spec-aug_speech-perturbations_26885397:latest/parakeet-tdt-0.6b-v3-finetune_spec-aug_speech-perturbations.nemo'
nemo_model: true
