defaults:
  - base_model

name: 'parakeet-tdt-0.6b-v3_finetune_spec-aug'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-tdt-0.6b-v3-finetune_26719246:latest/parakeet-tdt-0.6b-v3-finetune.nemo'
nemo_model: true