defaults:
  - base_model

name: 'parakeet_finetune_speed-perturbations'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-finetune_speed-perturbations_27154187:latest/parakeet-finetune_speed-perturbations.nemo'
nemo_model: true
