defaults:
  - base_model

name: 'parakeet_finetune_pitch-shift'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-finetune_pitch-shift_27111642:latest/parakeet-finetune_pitch-shift.nemo'
nemo_model: true