defaults:
  - base_model

name: 'parakeet-tdt-0.6b-v3_finetuned_spec-aug'

# Evaluation parameters
model_id: null
restore_from: 'artifact://parakeet-tdt-0.6b-v3-finetune_26719246:latest/parakeet-tdt-0.6b-v3-finetune.nemo'
nemo_model: true

decoding_config:
  strategy: 'malsd_batch'
  beam:
    ngram_lm_model: '/work3/s204071/master_thesis/kenlm_parakeet_0.6b.arpa.nemo'
    ngram_lm_alpha: 0.2
    beam_size: 12
    pruning_mode: 'late'
    blank_lm_score_mode: 'lm_weighted_full'
    allow_cuda_graphs: true
