ds_item:
  - name: coral
    manifest_filepath: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/CoRal-project_coral-v2_read-aloud/val/sharded_manifests/manifest__OP_0..3_CL_.json'
    tarred_audio_filepaths: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/CoRal-project_coral-v2_read-aloud/val/audio__OP_0..3_CL_.tar'
    is_tarred: true
    sample_rate: ${model.sample_rate}
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 2
    pin_memory: true
    log_prediction: ${model.log_prediction}

    force_map_dataset: true
    force_finite: true
    # bucketing params
    bucketing_strategy: 'fully_randomized'
    bucketing_batch_size: null
    use_lhotse: true
    batch_duration: 1100
    quadratic_duration: 30
    num_buckets: 30
    num_cuts_for_bins_estimate: 10000
    bucket_buffer_size: 10000
    shuffle_buffer_size: 10000
    text_field: 'text'
    lang_field: 'target_lang'

  - name: fleurs
    manifest_filepath: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/google_fleurs/validation/sharded_manifests/manifest__OP_0..1_CL_.json'
    tarred_audio_filepaths: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/google_fleurs/validation/audio__OP_0..1_CL_.tar'
    is_tarred: true
    sample_rate: ${model.sample_rate}
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 2
    pin_memory: true
    log_prediction: ${model.log_prediction}

    force_map_dataset: true
    force_finite: true
    # bucketing params
    bucketing_strategy: 'fully_randomized'
    bucketing_batch_size: null
    use_lhotse: true
    batch_duration: 1100
    quadratic_duration: 30
    num_buckets: 30
    num_cuts_for_bins_estimate: 10000
    bucket_buffer_size: 10000
    shuffle_buffer_size: 10000
    text_field: 'text'
    lang_field: 'target_lang'
