defaults:
  - model: canary-1b-v2_12-buckets_speech_perturbations
  - trainer: canary-1b-v2
  - exp_manager: base_finetune

name: 'canary-1b-v2-finetune_12-buckets_speech_perturbations'

seed: 15

# use `init_from_nemo_model` or `init_from_pretrained_model` to initialize the model
# We do not currently support `init_from_ptl_ckpt` to create a single script for all types of models.
init_from_pretrained_model: nvidia/canary-1b-v2 # path to nemo model

model:
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 0
    time_masks: 0
