manifest_filepath: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/LilleLyd/manifest_train.jsonl'
sample_rate: 16000

# bucketing params
use_lhotse: true
batch_size: 32
max_duration: 20
min_duration: 0.1

text_field: 'text'
lang_field: 'target_lang'

num_workers: 4
prefetch_factor: 2
pin_memory: true
shuffle_seed: ${seed}
seed: ${seed}
