defaults:
  - base_training_dataset
  - speech_perturbations

manifest_filepath: ${.speech_perturbations.sharded_manifest}
tarred_audio_filepaths: ${.speech_perturbations.tar_archives}

batch_size: 16
shuffle: true
