defaults:
  - dataset: coral
  - model: whisper-tiny
  - eval: base_eval
  - trainer: base_trainer

enable_wandb: true

hydra:
  run:
    dir: ./experiments/${hydra.job.name}/${model.name}_${dataset.name}_${dataset.dataset_subset}_${dataset.eval_split_name}/${now:%Y-%m-%d_%H-%M-%S}
