# Evaluation dataset parameters
dataset_id: "CoRal-project/coral-v2"
dataset_subset: "conversation"
eval_split_name: test
text_column: text
audio_column: audio
cache_dir: "./data/huggingface/datasets"

# Filtering of the dataset
min_seconds_per_example: 0.5
max_seconds_per_example: 10

# Processing of the dataset
clean_text: true
lower_case: true
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'

# Evaluation parameters
model_id: "openai/whisper-tiny"
no_lm: false  # This is only relevant for Wav2Vec 2.0 models
sampling_rate: 16_000
metrics:
  - cer
  - wer
batch_size: 1
store_results: true