# Evaluation dataset parameters
eval_split_name: test
cache_dir: './data/huggingface/datasets'

# Filtering of the dataset
filter: false
min_seconds_per_example: 0.5
max_seconds_per_example: 10

# Processing of the dataset
clean_text: true
lower_case: true
sampling_rate: 16_000

id_column: null

text_column: text
audio_column: audio

characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'
