defaults:
  - optim: adamw

sample_rate: 16000
log_prediction: false

char_labels:
  update_labels: false
  labels: null

tokenizer:
  update_tokenizer: false
  dir: null
  type: bpe

spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 10
  freq_width: 27
  time_width: 0.05
  use_numba_spec_augment: true
