defaults:
  - base_finetune
  - train_ds: lhotse_training_dataset_canary_40gb
  - validation_ds: lhotse_validation_dataset

preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  sample_rate: ${model.sample_rate}
  normalize: 'per_feature'
  window_size: 0.025
  window_stride: 0.01
  window: 'hann'
  features: 128
  n_fft: 512
  log: true
  frame_splicing: 1
  dither: 0.00001
  pad_to: 0
  pad_value: 0.0
