ds_item:
  - name: coral
    manifest_filepath: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/CoRal-project_coral-v2_read-aloud/val/tarred_audio_manifest.json'
    tarred_audio_filepaths: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/CoRal-project_coral-v2_read-aloud/val/audio__OP_0..3_CL_.tar'
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 2
    is_tarred: true
    log_prediction: false

  - name: fleurs
    manifest_filepath: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/google_fleurs/validation/tarred_audio_manifest.json'
    tarred_audio_filepaths: '${oc.env:NEMO_DATASET_PROCESSED_PATH}/google_fleurs/validation/audio__OP_0..1_CL_.tar'
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 2
    is_tarred: true
    log_prediction: false
